emergencyroom/emergencyroom/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('staff/', include('staff.urls')),
    path('', RedirectView.as_view(url='staff/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

emergencyroom/staff/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('patients/', views.PatientListView.as_view(), name='patients'),
    path('newPatient', views.create_patient_form, name='new_patient'),
    path('patient/<int:pk>', views.patient_view, name='patient-detail'),
    path('newContact/<int:pk>', views.emergency_contact_form, name='new_contact'),
    path('newSymptom/<int:pk>', views.symptom_form, name='new_symptom'),
    path('newMed/<int:pk>', views.medicine_form, name='new_med'),
    path('newTest/<int:pk>', views.test_form, name='new_test'),
    path('newAllergy/<int:pk>', views.allergy_form, name='new_allergy'),
    path('patient_nurse/<int:pk>', views.patient_nurse_form, name='patient_nurse_form'),
    path('patient_doctor/<int:pk>', views.patient_doctor_form, name='patient_doctor_form'),
    path('patient_bill/<int:pk>', views.bill_form, name='bill_form'),
    path('patient_bill_display/<int:pk>', views.print_bill, name='print_bill'),
    path('covid_shot/<int:pk>', views.create_covid_shot_form, name='create_covid_shot_form'),
    path('contact/<int:pk>/delete/', views.contact_delete, name='contact-delete'),
    path('covid_shot/<int:pk>/delete/', views.vaccine_delete, name='covid_shot-delete'),
    path('allergy/<int:pk>/delete/', views.allergy_delete, name='allergy-delete'),
    path('symptom/<int:pk>/delete/', views.symptom_delete, name='symptom-delete'),
    path('test/<int:pk>/delete/', views.test_delete, name='test-delete'),
    path('patient/<int:pk>/delete/', views.patient_delete, name='patient-delete'),
    path('med/<int:pk>/delete/', views.medicine_delete, name='medicine-delete'),
    path('diagnose/<int:pk>', views.create_diagnose_form, name='create_diagnose_form'),
    path('diagnose/<int:pk>/delete/', views.diagnose_delete, name='diagnose-delete'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

emergencyroom/staff/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models
import uuid
from decimal import Decimal
from django.urls import reverse
from django.core.validators import RegexValidator


class Patient(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4())
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    insurance_provider = models.CharField(max_length=40, null=True, blank=True)
    primary_doctor_name = models.CharField(max_length=40, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    height = models.FloatField(help_text='Height in cm', validators=[MinValueValidator(Decimal('0.01'))], null=True, blank=True)
    weight = models.FloatField(help_text='Weight in kg,', validators=[MinValueValidator(Decimal('0.01'))],  null=True, blank=True)
    heart_rate = models.PositiveIntegerField(null=True,  blank=True)
    blood_pressure_upper = models.PositiveIntegerField(null=True,  blank=True)
    blood_pressure_lower = models.PositiveIntegerField(null=True,  blank=True)
    religious_restriction = models.TextField( blank=True)
    doctor_note = models.TextField(null=True, blank=True)
    nurse_note = models.TextField(null=True, blank=True)
    nights_stayed = models.PositiveSmallIntegerField(default=0, blank=True)
    # bill = models.PositiveBigIntegerField()
    drug_usage = models.BooleanField(null=True, blank=True)
    discharge_instructions = models.TextField(null=True, blank=True)
    gender_options = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    gender = models.CharField(max_length=1,
                              choices=gender_options,
                              blank=True, )
    race = models.CharField(null=True, max_length=20, blank=True)
    sexual_active = models.BooleanField(null=True, blank=True)
    IV = models.BooleanField(null=True, blank=True)
    blood_type_options = (
        ('1', 'O negative'),
        ('2', 'O positive'),
        ('3', 'A negative'),
        ('4', 'A positive'),
        ('5', 'B negative'),
        ('6', 'B positive'),
        ('7', 'AB negative'),
        ('8', 'AB  positive'),
    )
    blood_type = models.CharField(max_length=1,
                                  choices=blood_type_options,
                                  blank=True,
                                  )

    # doctor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    bill_due_date = models.DateField(null=True, blank=True)

    class Meta:
        permissions = (('doctor', 'Is a doctor'),
                       ('nurse', 'Is a nurse'),
                       ('medical professional', 'Is a nurse or doctor'),
                       ('billing', 'Is at the billing desk'),
                       ('registration', 'is a registrar desk'),
                       ('not billing', 'is not billing'))
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('patient-detail', args=[str(self.id)])

    def get_contact_link(self):
        return reverse('new_contact', args=[str(self.id)])

    def get_symptom_link(self):
        return reverse('new_symptom', args=[str(self.id)])

    def get_med_link(self):
        return reverse('new_med', args=[str(self.id)])

    def get_test_link(self):
        return reverse('new_test', args=[str(self.id)])

    def get_diagnose_link(self):
        return reverse('create_diagnose_form', args=[str(self.id)])

    def get_allergy_link(self):
        return reverse('new_allergy', args=[str(self.id)])

    def get_nurse_url(self):
        return reverse('patient_nurse_form', args=[str(self.id)])

    def get_doctor_url(self):
        return reverse('patient_doctor_form', args=[str(self.id)])

    def get_bill_form_url(self):
        return reverse('bill_form', args=[str(self.id)])

    def get_bill_display_url(self):
        return reverse('print_bill', args=[str(self.id)])

    def get_covid_shot_url(self):
        return reverse('create_covid_shot_form', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

    def get_delete_url(self):
        return reverse('patient-delete', args=[str(self.id)])


class Symptom(models.Model):
    symptom = models.CharField(max_length=20)
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE)

    def get_delete_url(self):
        return reverse('symptom-delete', args=[str(self.id)])


class Allergy(models.Model):
    allergy = models.CharField(max_length=20)
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE)

    def get_delete_url(self):
        return reverse('allergy-delete', args=[str(self.id)])

class Test(models.Model):
    test_options = (
        ('A', 'Hematologic Laboratory'),
        ('B', 'Red blood cell '),
        ('C', 'White blood cell'),
        ('D', 'Liver function test'),
        ('E', 'Renal function test'),
        ('F', 'Electrolyte test'),
        ('G', 'Radiologic Laboratory'),
        ('H', 'X-ray'),
        ('I', 'Computed Tomography (CT)'),
        ('J', 'Magnetic Resonance Image (MRI)'),
        ('K', 'Urinary Test'),
        ('L', 'Stool Test'),
    )
    test = models.CharField(max_length=1,
                            choices=test_options)
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE)
    cost = models.FloatField(help_text='', validators=[MinValueValidator(Decimal('0.01'))])

    def get_delete_url(self):
        return reverse('test-delete', args=[str(self.id)])

class Medication(models.Model):
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE)
    medicine_options = (
        ('A', 'Insulin'),
        ('B', 'Candesartan'),
        ('C', 'Dexamethasone'),
        ('D', 'Azithromycin'),
        ('E', 'Fluticasone'),
        ('F', 'Alteplase'),
        ('G', 'Aspirin'),
    )

    medicine = models.CharField(max_length=1,
                                choices=medicine_options, null=False)
    dosage = models.FloatField(help_text='Dosage in mg', validators=[MinValueValidator(Decimal('0.01'))])
    cost = models.FloatField(help_text='', validators=[MinValueValidator(Decimal('0.01'))])

    def get_delete_url(self):
        return reverse('medicine-delete', args=[str(self.id)])


class EmergencyContact(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)  # Validators should be a list

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

    def get_delete_url(self):
        return reverse('contact-delete', args=[str(self.id)])


class Diagnose(models.Model):
    diagnose_options = (
        ('A', 'Diabetes'),
        ('B', 'Hypertension'),
        ('C', 'Covid'),
        ('D', 'Pneumonia'),
        ('E', 'Asthma'),
        ('F', 'Stroke'),
        ('G', 'Heart attack'),
    )
    diagnose = models.CharField(max_length=1,
                                choices=diagnose_options)
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE)

    def get_delete_url(self):
        return reverse('diagnose-delete', args=[str(self.id)])


class CovidVaccineShot(models.Model):
    brand_options = (
        ('P', 'Pfizer'),
        ('M', 'Moderna'),
        ('A', 'AstraZeneca'),
        ('J', '	Johnson & Johnson'),
        ('N', 'Novavax'),
        ('R', 'Not taken'),
    )
    brand = models.CharField(max_length=1,
                             choices=brand_options)
    date_received = models.DateField()
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE)

    def __str__(self):
        return 'Brand: {brand} \n Date Recieved: {date}'.format(brand=self.brand, date=self.date_received)

    def get_delete_url(self):
        return reverse('covid_shot-delete', args=[str(self.id)])

emergencyroom/staff/forms.py
from django import forms
from .models import Patient, EmergencyContact, Symptom, Medication, Test, Allergy, CovidVaccineShot, Diagnose


class EmergencyContactForm(forms.ModelForm):
    class Meta:
        model = EmergencyContact
        fields = ('first_name', 'last_name', 'patient', 'phone_number')


class DiagnoseForm(forms.ModelForm):
    class Meta:
        model = Diagnose
        fields = '__all__'


class PatientNurseForm(forms.ModelForm):
    class Meta:
        model = Patient
        exclude = ('doctor_note', 'discharge_instructions', 'bill_due_date')


class PatientDoctorForm(forms.ModelForm):
    class Meta:
        model = Patient
        exclude = ('nurse_note', 'bill_due_date')


class SymptomForm(forms.ModelForm):
    class Meta:
        model = Symptom
        fields = '__all__'


class MedicineForm(forms.ModelForm):
    class Meta:
        model = Medication
        fields = '__all__'


class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = '__all__'


class AllergyForm(forms.ModelForm):
    class Meta:
        model = Allergy
        fields = '__all__'


class CreatePatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ('first_name', 'last_name', 'date_of_birth', 'height', 'weight', 'religious_restriction',
                  'drug_usage', 'discharge_instructions', 'gender', 'race', 'sexual_active', 'blood_type', 'insurance_provider')


class SetBillDateForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ('bill_due_date',)


class CovidShotForm(forms.ModelForm):
    class Meta:
        model = CovidVaccineShot
        fields = '__all__'

emergencyroom/staff/templates/staff/display_bill.html
{% extends "base_generic.html" %}
{% load auth_extras %}

{% block content %}
    {% if test_list %}
<h3>Bill for: {{patient.first_name}} {{patient.last_name}}</h3>
<h3>Due Date: {{patient.bill_due_date}}</h3>
<br>
<h4>Number of Nights Stayed: {{patient.nights_stayed}}</h4>
<h4>Cost Per Night: $150</h4>

<br>
<h4>Tests: </h4>
           {% for test in test_list %}
           <li>
             <a >{{test.get_test_display}}: ${{test.cost}} </a>
           </li>
     {%  endfor %}
     {% endif %}

<br>

<h4>Medicine: </h4>
           {% for med in medication_list %}
           <li>
             <a >{{med.get_medicine_display}}: ${{med.cost}} </a>
           </li>
     {%  endfor %}

<br>
<h4>Total cost of overnight stay: ${{night_cost}}</h4>
<h4>Total Test Cost: ${{total_test_cost}}</h4>
<h4>Total Medicine Cost: ${{total_med_cost}}</h4>
<h1>Total Cost: ${{total_cost}}</h1>



{% endblock %}

emergencyroom/staff/templates/staff/emergencycontact_form.html
{% extends "base_generic.html" %}

{% block content %}
<div class="loginpage">
  <h1>Add New Patient</h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <div class="submitbutton">
       <input type="submit" value="Submit">
      </div>
  </form>
  </div>
{% endblock %}

emergencyroom/staff/templates/staff/form_form.html
{% extends "base_generic.html" %}

{% block content %}
<div class="emergencyform">
      <h1>Edit Patient</h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>

        <div class="submitbutton">
       <input type="submit" value="Submit">
      </div>
  </form>
</div>
{% endblock %}

emergencyroom/staff/templates/staff/patient_detail.html
{% extends "base_generic.html" %}
{% load auth_extras %}

{% block content %}
<h1>Patient Details for {{ patient.first_name }}{{" "}}{{ patient.last_name }}</h1>


<div class="buttons">
{% if request.user|has_group:'doctors' %}
<button type="button">
   <a href={{patient.get_doctor_url}}>Edit Patient</a>
</button>

{% endif %}
{% if request.user|has_group:'billing' %}
<button type="button">
   <a href={{patient.get_bill_form_url}}>Set Bill Date</a>
</button>

<h3>Bill Due {{ patient.bill_due_date }}</h3>
<button type="button">
    <a href={{patient.get_bill_display_url}}>View Bill</a>
</button>

{% endif %}
</div>

<h2>Basic Details</h2>
<h3>First name: {{ patient.first_name }}</h3>
<h3>Last name: {{ patient.last_name }}</h3>
<h3>Date of Birth: {{ patient.date_of_birth }}</h3>
{% if not request.user|has_group:'billing' %}
<h3>Height: {{ patient.height }} cm</h3>
<h3>Weight: {{ patient.weight }} kg</h3>
<h3>Gender: {{ patient.get_gender_display }}</h3>
<h3>Race: {{ patient.race }}</h3>
<h3>Sexually Active: {{ patient.sexual_active }}</h3>
<h3>Health Insurance Provider: {{ patient.insurance_provider }}</h3>
{% if request.user|has_group:'medical_professional' %}
<h3>Doctor: {{ patient.primary_doctor_name }}</h3>
<br>

<h2>Vitals</h2>
<h3>Heart Rate: {{ patient.heart_rate }} bpm </h3>
<h3>Blood Pressure: (Upper) {{ patient.blood_pressure_upper }} mmHg</h3>
<h3>Blood Pressure: (Lower) {{ patient.blood_pressure_lower }} mmHg</h3>
{%endif%}
<h3>Religious Restrictions: {{ patient.religious_restriction }}</h3>
{% if request.user|has_group:'medical_professional' %}

{%endif%}

{% if request.user|has_group:'medical_professional' %}

<h3>IV: {{ patient.IV }}</h3>
{% endif %}

<h3>Blood Type: {{ patient.get_blood_type_display }}</h3>
<h3>Drug Usage: {{ patient.drug_usage }}</h3>

<br>
<h2>Notes</h2>
<h3>Doctor Notes: {{ patient.doctor_note }}</h3>
<h3>Nurse Notes: {{ patient.nurse_note }}</h3>
{% if request.user|has_group:'medical_professional' %}
<h3>Discharge Instructions: {{ patient.discharge_instructions }}</h3>
{%endif%}
<h3>Number of Nights Stayed: {{ patient.nights_stayed }} nights</h3>

<br>

<h2>Covid Vaccines: </h2>
{% if covid_vaccine_list %}
{% for vaccine in covid_vaccine_list %}
<li>
    <a>Brand: {{vaccine.get_brand_display}}</a>
    <a>Date Recieved: {{vaccine.date_received}}</a>
    <a href={{vaccine.get_delete_url}}>Delete</a>
</li>
{%  endfor %}
{% else %}
<h3>This patient is not vaccinated.</h3>
{% endif %}
<a href={{patient.get_covid_shot_url}}>new vaccine</a>
<br>

<br>
{% if request.user|has_group:'medical_professional' %}
    <h2>Medication: </h2>
    {% if medication_list %}
    {% for med in medication_list %}
    <li>
        <a>{{med.get_medicine_display}}</a>
        <a>Dosage: {{med.dosage}} mg</a>
        <a href={{med.get_delete_url}}>Delete</a>

    </li>
    {% endfor %}
    {% else %}
    <h3>This patient is not on any medication.</h3>
    {% endif %}
    <a href={{patient.get_med_link}}>new medication</a>

{% endif %}
<br>
<br>
<h2>Emergency Contacts: </h2>
{% if emergency_contact_list %}
{% for contact in emergency_contact_list %}
<li>
    <a>Name: {{contact.first_name}} {{contact.last_name}} Phone number: {{contact.phone_number}}</a>
    <a href={{contact.get_delete_url}}>Delete</a>
</li>
{%  endfor %}
{% else %}
<h3>This patient has no emergency contacts.</h3>
{% endif %}
<a href={{patient.get_contact_link}}>new contact</a>
<br>
<br>

<h2>Symptoms: </h2>
{% if symptom_list %}
{% for symptom in symptom_list %}
<li>
    <a>{{symptom.symptom}}</a>
    <a href={{symptom.get_delete_url}}>Delete</a>

</li>
{%  endfor %}
{% else %}
<h3>This patient has no symptoms.</h3>
{% endif %}
<a href={{patient.get_symptom_link}}>new symptom</a>
<br>
<br>
<h2>Allergies: </h2>
{% if allergy_list %}
{% for allergy in allergy_list %}
<li>
    <a>{{allergy.allergy}}</a>
    <a href={{allergy.get_delete_url}}>Delete</a>

</li>
{%  endfor %}
{% else %}
<h3>This patient has no allergies.</h3>
{% endif %}
<a href={{patient.get_allergy_link}}>new allergy</a>
<br>
<br>
<h2>Tests: </h2>
{% if test_list %}
{% for test in test_list %}
<li>
    <a>{{test.get_test_display}} </a>
    <a href={{test.get_delete_url}}>Delete</a>
</li>
{%  endfor %}
{% else %}
<h3>This patient has no tests.</h3>
{% endif %}
{% endif %}
{% if request.user|has_group:'doctors' %}
<a href={{patient.get_test_link}}>new test</a>
<br>

<h2>Diagnoses: </h2>
{% if diagnosis_list %}
{% for diagnose in diagnosis_list %}
<li>
    <a>{{diagnose.get_diagnose_display}} </a>
    <a href={{diagnose.get_delete_url}}>Delete</a>
</li>
{%  endfor %}
{% else %}
<h3>This patient has no diagnoses.</h3>
{% endif %}
{% endif %}
{% if request.user|has_group:'doctors' %}
<a href={{patient.get_diagnose_link}}>new diagnose</a>
<br>


{% if request.user|has_group:'nurses' %}
{% endif %}

{% endif %}

{% endblock %}

emergencyroom/staff/templates/staff/patient_form.html
{% extends "base_generic.html" %}

{% block content %}
<div class="emergencyform">

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>

        <div class="submitbutton">
       <input type="submit" value="Submit">
      </div>
  </form>
</div>
{% endblock %}

emergencyroom/staff/templates/staff/patient_list.html
{% extends "base_generic.html" %}

{% block content %}
  <div class=patientList">
     <h1 id="pageTitle">Patient List</h1>
     {% if patient_list %}
     {% for patient in patient_list %}

         <table class="table">
            <tr>
              <td> <a href={{patient.get_absolute_url}}>{{ patient.first_name }}{{" "}}{{ patient.last_name }} </a> </td>
              <td> <a href={{patient.get_delete_url}}> Delete</a> </td>
            </tr>
          </table>
        {% endfor %}
      {% else %}
        <p>There are no patients.</p>
      {% endif %}
  </div>
{% endblock %}

emergencyroom/staff/templates/staff/register_emergency_patient.html
{% extends "base_generic.html" %}

{% block content %}

{% endblock %}